# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CKL iOS Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Makes REST requests:
  pod 'Alamofire', '4.7.3'
  pod 'PKHUD', '5.2.0'
  pod 'SwiftyJSON', '4.2.0'
  pod 'Kingfisher', '4.10.0'

end
